### ISSUE TITLE
Missing apps icons

### ISSUE THREAD

**Issue by rosenpin** [wernjie/clarity#1]
Some icons are missing for apps  
Is there a precompiled list of icons? or are they collected at runtime?  
Specifically an icon for Adobe premiere and Android studio are missing  
<img width="719" alt="image" src="https://user-images.githubusercontent.com/5289630/218843672-699e36f4-b711-418d-86a4-a413c147e82f.png">
![image](https://user-images.githubusercontent.com/5289630/218843782-59199535-ad12-4364-9a6e-f9b9c0cdd378.png)

**Comment by rosenpin** [comment]
This seems like it might be the issue

<img width="705" alt="image" src="https://user-images.githubusercontent.com/5289630/218847257-055a74b7-b794-4e37-97cd-83546c64d4e9.png">

Corresponding code
<img width="709" alt="image" src="https://user-images.githubusercontent.com/5289630/218847294-ec3fcda1-7dda-4815-8d3c-5558e3349c72.png">

**Comment by rosenpin** [comment]
Figured it out, you should reconsider modifying this part in the `prepAppIconScript`:   
<img width="509" alt="image" src="https://user-images.githubusercontent.com/5289630/218850287-a4b7319b-6c33-4729-84ff-e925e08f32f8.png">  

Either add more paths (like jetbrains in my example) or make it dynamically find the path

**Comment by rosenpin** [comment]
I fixed it by replacing the for loop you had with a nested search (fixes the issue for most apps like adobe apps/apps installed using jetbrains toolbox etc)

I opened a PR #2

**Comment by wxwern** [comment]
Yep that seems right, apps that are installed in their own subdirectories won't be found but can be resolved by searching subdirectories as well. 

I'll look through and merge your PR!
